### PR TITLE
Adding spanish translation

### PR DESCRIPTION
**Pull request by jvas28**

### CODE REVIEW

**Comment by Bottelet** [comment]
Sorry @jvas28 I haven't forgotten the PR yet, I just have to come up with a way to keep language files in sync, in case I add new translations

**Comment by jvas28** [comment]
@Bottelet no problem

**Comment by jvas28** [comment]
@Bottelet there's one more complete PR being done for this. Not sure if it makes sense to keep this open.

**Comment by Bottelet** [comment]
@jvas28 Thanks, I'll let you be in control of the other PR, seems like you have good control of it :) Cheers Thanks!

**Pull request closed without merging**
