### PR TITLE
[master]Create button on list page

### PR DESCRIPTION
**Pull request by alamriku**

### CODE REVIEW

**Comment by Bottelet** [comment]
@alamriku If you split up the translation and changes into two PR I'll gladly approve the PR with the changes.

**Comment by alamriku** [comment]
@Bottelet. make two separate PR only on the translation branch? is it what you mean? Pardon me if I misunderstood.

**Comment by Bottelet** [comment]
I mean two separate branches and two separate PRS one for localization, and on for the other. @alamriku

**Comment by alamriku** [comment]
when I want to create pull request for translation I can't create pull request..why? can you help me?
see the attach image.
compareDaybyDayCRM

**Pull request closed without merging**
