### PR TITLE
Fix unprivileged user can edit roles.

### PR DESCRIPTION
**Pull request by rm-yakovenko**
Currently, an unprivileged user can edit roles and promote himself to the administrator.

### CODE REVIEW

**Comment by Bottelet** [comment]
I think update is correct, but I feel like everyone should be able to see roles, or lets at least make it permissions based, so that admin can choose if it should be possible? What do you think?

**Comment by rm-yakovenko** [comment]
For me, it's hard to answer. I think it should depend on the customers' needs.

I would leave it as it is now - only admin can edit roles.  If some customers asked to make it permission-based, I would consider it. 

The code is written very well so I don't think it will take a lot of time to refactor it.

**Comment by Bottelet** [comment]
All right, I think I agree with the change @rm-yakovenko, but we have to add an @if statement, on the sidebar menu, inside master.blade.php, so users can't click the link unless admin then

**Comment by rm-yakovenko** [comment]
Looks like the if statement is already present

https://github.com/Bottelet/DaybydayCRM/blob/develop/resources/views/layouts/master.blade.php#L136

**Comment by Bottelet** [comment]
You are right sorry, looks fine to me ;)

**Comment by Bottelet** [comment]
Thanks!

**Pull request merged**
